# Shared projector defaults for all methods.
model:
  # Projector MLP controls live here; methods may add predictor.
  projector_hidden: 2048
  projector_out: 128
  predictor_hidden: 1024
  predictor_out: 256

