provenance: true
nvtx: false
timing:
  enabled: true
  warmup_steps: 50
  sample_rate: 1
comms_log:
  enabled: true
memory:
  enabled: true
  step_interval: 10
energy:
  enabled: false
  kwh_price_usd: 0.25
  sample_interval_s: 1.0
mixture:
  enabled: false
  K: 8
  mode: ema
  assigner: kmeans_online
  ema_decay: 0.95
  store_scores: false
  scores_mode: append
  cross_rank: false
  max_assign_iters: 2
  # Top-R diagnostics
  topR: 0                 # 0 = measure only, don't truncate
  pi_floor: 1.0e-3        # floor before normalizing pi for Top-R
  K_subsample: null       # optional chunk size for big-K log-sum-exp
beta_ctrl:
  enabled: false
  target_mix_inflation_eps: 0.05
  beta_min: 3
  beta_max: 12
  ema_window: 50
stability:
  enabled: false
  history_steps: 100
budget:
  enabled: false
  mode: iso_time
  max_minutes: null
  max_tokens: null
  max_epochs: null
  max_comm_bytes: null
  max_energy_Wh: null
  steps_per_epoch: null
