provenance: true
nvtx: false
timing:
  enabled: true
  warmup_steps: 50
  sample_rate: 1
comms_log:
  enabled: true
memory:
  enabled: true
  step_interval: 10
energy:
  enabled: false
  kwh_price_usd: 0.25
  sample_interval_s: 1.0
